# Generated by Django 4.2.11 on 2024-04-27 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0002_rename_id_company_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('fax', models.CharField(default=None, max_length=100)),
                ('website', models.TextField(default=None)),
                ('source', models.CharField(max_length=100)),
                ('about', models.TextField(default=None)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city_code', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('attached_contract', models.FileField(null=True, upload_to='media/client_contract')),
                ('attached_other', models.FileField(null=True, upload_to='media/client_other')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
    ]
