# Generated by Django 4.2.11 on 2024-04-26 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0002_rename_id_company_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('office_shift', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('attendance_type', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.FileField(null=True, upload_to='media/employee_image')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
    ]
