# Generated by Django 4.2.11 on 2024-04-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_immigration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Immigration',
        ),
    ]
