# Generated by Django 4.2.11 on 2024-04-30 12:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryDeductions',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_year', models.DateField()),
                ('deduction_option', models.CharField(max_length=100)),
                ('deduction_title', models.CharField(max_length=100)),
                ('deduction_amount', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPension',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pension_type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_year', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('number_of_days', models.CharField(max_length=100)),
                ('total_hours', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='OtherPayments',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_year', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_year', models.DateField()),
                ('loan_option', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('number_of_installment', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Commissions',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_year', models.DateField()),
                ('commission_title', models.CharField(max_length=100)),
                ('commission_amount', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BasicSalary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_year', models.DateField()),
                ('payslip_type', models.CharField(max_length=100)),
                ('basic_salary', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Allowances',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_year', models.DateField()),
                ('allowance_type', models.CharField(max_length=100)),
                ('allowance_title', models.CharField(max_length=100)),
                ('allowance_amount', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
    ]
