# Generated by Django 4.2.11 on 2024-05-07 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0009_statutorydeductions_salarypension_overtime_and_more'),
        ('Company', '0002_rename_id_company_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('promotion_date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(default=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
    ]
