# Generated by Django 4.2.11 on 2024-05-08 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0009_statutorydeductions_salarypension_overtime_and_more'),
        ('Company', '0002_rename_id_company_uuid'),
        ('CoreHR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warning_to', models.CharField(max_length=100)),
                ('warning_type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('warning_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrangement_type', models.CharField(max_length=100)),
                ('purpose_of_visit', models.CharField(max_length=100)),
                ('plcae_of_visit', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_budget', models.CharField(max_length=100)),
                ('actual_budget', models.CharField(max_length=100)),
                ('travel_mode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_department', models.CharField(max_length=100)),
                ('to_department', models.CharField(max_length=100)),
                ('transfer_date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(default=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('termination_to', models.CharField(max_length=100)),
                ('termination_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('termination_date', models.DateField(default=datetime.date.today)),
                ('notice_date', models.DateField(default=datetime.date.today)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('notice_date', models.DateField(default=datetime.date.today)),
                ('resignation_date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(default=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_from', models.CharField(max_length=100)),
                ('complaint_against', models.CharField(max_length=100)),
                ('complaint_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('complaint_date', models.DateField(default=datetime.date.today)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('award_type', models.CharField(max_length=100)),
                ('gift', models.CharField(max_length=100)),
                ('cash', models.CharField(max_length=100)),
                ('award_information', models.TextField()),
                ('award_date', models.DateField(default=datetime.date.today)),
                ('award_photo', models.FileField(null=True, upload_to='media/award_photo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.employee')),
            ],
        ),
    ]
