# Generated by Django 4.2.11 on 2024-05-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreHR', '0004_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='action',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
