# Generated by Django 4.2.11 on 2024-04-24 13:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('treading_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('website', models.TextField(default=None)),
                ('location', models.CharField(max_length=100)),
                ('tax_number', models.CharField(max_length=100)),
                ('company_logo', models.FileField(null=True, upload_to='media/company_logo')),
                ('created_on', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
