# Generated by Django 4.2.11 on 2024-05-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_rename_id_company_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.TextField(default=None, null=True),
        ),
    ]
