# Generated by Django 4.2.11 on 2024-05-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_company_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='registration_number',
            new_name='gst_number',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tax_number',
            new_name='pancard_number',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='line_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pin_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='signature_of_admin',
            field=models.FileField(null=True, upload_to='media/signature'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tin_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
