# Generated by Django 4.2.11 on 2024-05-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_rename_location_company_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='email',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='phone_number',
            new_name='admin_phone_number',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tin_number',
            new_name='tan_number',
        ),
        migrations.AddField(
            model_name='company',
            name='admin_designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='admin_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
